[package]
name = "marduk"
version = "0.1.0"
authors = ["Matthew Maurer <matthew.r.maurer@gmail.com>"]

[dependencies]
num-traits = "0.1"
mktemp = "0.3"

[dependencies.mycroft]
path = "../mycroft"

[dependencies.mycroft-support]
path = "../mycroft/mycroft-support"

[dependencies.mycroft-macros]
path = "../mycroft/mycroft-macros"

[dependencies.bap]
git = "https://github.com/maurer/bap-rust"
