[package]
name = "marduk"
version = "0.1.0"
authors = ["Matthew Maurer <matthew.r.maurer@gmail.com>"]

[dependencies]
num-traits = "0.1"
mktemp = "0.3"
log = "0.4"
env_logger = "0.5"
lazy_static = "1.0"

[dependencies.mycroft]
git = "https://github.com/maurer/mycroft.git"

[dependencies.mycroft-support]
git = "https://github.com/maurer/mycroft.git"

[dependencies.mycroft-macros]
git = "https://github.com/maurer/mycroft.git"

[dependencies.bap]
git = "https://github.com/maurer/bap-rust"

[profile.release]
debug = true
