[package]
name = "marduk"
version = "0.1.0"
authors = ["Matthew Maurer <matthew.r.maurer@gmail.com>"]

[dependencies]
num-traits = "0.1"
mktemp = "0.3"
log = "0.4"
env_logger = "0.5"
lazy_static = "1.0"
bap = "0.1"
mycroft = "0.0.1"
mycroft-support = "0.0.1"
mycroft-macros = "0.0.1"

[profile.release]
debug = true
